# Dependencies required to build the docs
channels:
 - conda-forge
 - plotly
 - agilescience
dependencies:
  - agiletools==BUILD25ai
  - agilepy-dataset
  - astropy==4.*
  - plotly==4.*
  - psutil==5.*
  - matplotlib==3.*
  - pandas==1.*
  - ipympl==0.*
  - numpy==1.*
  - scipy==1.*
  - sphinx==2.*
  - sphinx_rtd_theme==0.4.3
  - pyyaml==5.*
  - regions
  - pytest-cov==2.*
  - python-kaleido==0.*
  - tqdm==4.*
