# Dependencies required to build the docs
channels:
 - conda-forge
 - plotly
 - agilescience
dependencies:
  - agiletools==BUILD25ai
  - agilepy-dataset
  - astropy==4.1
  - plotly==4.14.3
  - psutil==5.7.3
  - matplotlib==3.3.3
  - pandas==1.1.4
  - ipympl==0.8.8
  - numpy==1.19.4
  - scipy==1.5.3
  - sphinx==2.4.4
  - sphinx_rtd_theme==0.4.3
  - pyyaml==5.3.1
  - regions
  - pytest-cov==2.12.1
  - python-kaleido==0.0.3
  - tqdm==4.63.0
