input:
  evtfile: "$AGILE/agilepy-test-data/evt_index/agile_proc3_fm3.119_asdc2_EVT.index"
  logfile: "$AGILE/agilepy-test-data/log_index/agile_proc3_data_asdc2_LOG.log.index"

output:
  outdir: "$AGILE/agilepy-test-data/unittesting-output/config"
  filenameprefix: "testcase"
  logfilenameprefix: "testcase"
  verboselvl: 1

selection:
  tmin: 456361778
  tmax: 456537945
  timetype: "TT"
  glon: 80
  glat: 0

maps:
  energybins:
    - 100, 300

  fovbinnumber: 1
  binsize: 0.2

model:
  galcoeff: null
  isocoeff: null
