output:
  outdir: $TEST_LOGS_DIR
  filenameprefix: testcase
  logfilenameprefix: testcase
  sourcename: source-test
  username: user-test
  verboselvl: 2

selection:
  ap_path: null
  mle_path: null
  ph_path: null
  rate_path: null
  rate: null
  ratefactor: null
  detections_csv_path: null
  event_id: null
  tstart: null
  tstop: null

bayesianblocks:
  fitness: null
  p0: null
  gamma: null
  useerror: true