# Dependencies required to build the docs
channels:
 - conda-forge
 - plotly
 - agilescience
dependencies:
  - python==3.8.13
  - astropy
  - plotly
  - psutil
  - connected-components-3d
  - agiletools==BUILD25b3
  - agilepy-dataset
  - matplotlib
  - pandas
  - ipympl
  - numpy
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinx-copybutton
  - pyyaml
  - regions
  - pytest-cov
  - python-kaleido
  - tqdm