input:
  evtfile : null
  logfile : null

output:
  outdir: null
  filenameprefix: null
  logfilename: null
  debuglvl: 1

selection:
  emin: 100
  emax: 1000
  glat: null
  glon: null
  tmin: null
  tmax: null
  timetype: null
  timelist: None
  projtype: WCS
  proj: ARC
  filtercode: 5
  fovradmin: 0
  fovradmax: 60
  albedorad: 80
  dq: 0
  phasecode: null
  # Hidden parameters
  lonpole: 180
  lpointing: null
  bpointing: null
  maplistgen: "None"

maps:
  mapsize: 40
  useEDPmatrixforEXP: yes
  expstep: null
  spectralindex: 2.1
  timestep: 160
  # skytype: 4
  binsize: 0.1
  energybins:
    - [100, 10000]
  fovbinnumber: 1
  # Hidden parameters
  offaxisangle: 30

model:
  modelfile: null
  galmode: 1
  isomode: 1
  galcoeff: -1
  isocoeff: -1
  emin_sources: 100
  emax_sources: 10000
  # Advanced parameters
  galmode2: 0
  galmode2fit: 0
  isomode2: 0
  isomode2fit: 0

mle:
  ranal: 10
  ulcl: 2
  loccl: 95
  # Parameters for exp ratio evaluation
  expratioevaluation: yes
  expratio_minthr: 0
  expratio_maxthr: 15
  expratio_size: 10
  # Hidden for optimizer
  minimizertype: Minuit
  minimizeralg: Migrad
  minimizerdefstrategy: 2
  mindefaulttolerance: 0.01
  integratortype: 1
  contourpoints: 40
  # Hidden for internal corrections
  edpcorrection: 0.75
  fluxcorrection: 1
