package:
  name: "agiletools"
  version: "{{SCIENCE_TOOLS_TAG}}"

source:
  git_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  git_rev: "{{SCIENCE_TOOLS_TAG}}"

build:
  number: 0
  script_env:
    - SCIENCE_TOOLS_TAG

requirements:
  host:
    - python==3.8.13
    - cfitsio==4.1
    - gxx
    - root_base==6.26.6
    - zlib
    - make
    - binutils
    #- gsl==2.6
    #- libgcc-ng==9.1.0  # [linux]
  run:
    - python==3.8.13
    - cfitsio==4.1
    - root_base==6.26.6
    - zlib
    #- gsl==2.6
    - ruby==2.*
    #- libgcc-ng==9.1.0  # [linux]


about:
  home: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
  license: GPL-3.0
  summary: 'AGILE Python Analysis Framework.'
  description: |
    The software environment for Agilepy.
  dev_url: https://github.com/AGILESCIENCE/AGILE-GRID-ScienceTools-Setup.git
