name: new_release
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  setup:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: $GITHUB_REF

      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: True
          conda-channels: conda-forge, addis.inaf

      - name: Conda info
        run: |
          which python
          conda --version

      - name: Installing conda-build
        run: |
          conda install conda-build
          conda update conda-build

      - name: Download Agilepy-recipe
        run: git clone https://github.com/AGILESCIENCE/Agilepy-recipe.git





  build:
    steps:
      - name: First step
        run: echo Yo


  testing:
    steps:
      - name: First step
        run: echo Yo

  deploy:
    steps:
      - name: First step
        run: echo Yo
