name: Continuos integration workflow

on:
  push:
    branches:
      - ci_test_setup_miniconda

jobs:
  building:
    name: Building on (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
        
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: .github/environment.yml
          activate-environment: agilepydevops

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Running unit tests and code coverage
        run: |
          conda activate agilepydevops
          python setup.py develop
          printf "import pkg_resources \npath = pkg_resources.require('agilepy')[0].location \nprint(path+'/agilepy')" > get_agilepy_installation_folder.py
          agilepy_path=$((python get_agilepy_installation_folder.py) 2>&1)
          bash $agilepy_path/scripts/start_coverage.sh

      - name: Uploading coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_PROJECT_NAME: ${{ secrets.CODACY_PROJECT_NAME }}
          CODACY_USERNAME: ${{ secrets.CODACY_USERNAME }}
        run: |
          LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"	
          curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-linux"	
          chmod +x codacy-coverage-reporter	
          source ~/.bashrc	
          conda activate agilepydevops	
          agilepy_path=$((python get_agilepy_installation_folder.py) 2>&1)	
          ./codacy-coverage-reporter report -l Python -r $agilepy_path/testing/unittesting/coverage/cov_xml_report --commit-uuid "$GITHUB_SHA"
