name: Continuous integration workflow

on:
  push:
    branches:
      - develop
      - master
      #- feature-*

jobs:

  building-testing-on-os-matrix:
    name: Build+Test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-18.04", "macos-10.15"] #, "macos-11.0"]
        python-version: ["3.7"]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: .github/environment.yml
          activate-environment: agilepydevops

      - name: Installing Agilepy
        shell: bash -l {0}
        run: python setup.py develop

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Running unit tests and code coverage
        shell: bash -l {0}
        run: |
          printf "import pkg_resources \npath = pkg_resources.require('agilepy')[0].location \nprint(path+'/agilepy')" > get_agilepy_installation_folder.py
          agilepy_path=$((python get_agilepy_installation_folder.py) 2>&1)
          bash $agilepy_path/scripts/start_coverage.sh


  building-testing-on-os-centos7:

    name: Build+Test centos:7.7.1908 + Codacy

    runs-on: ubuntu-20.04

    container: centos:7.7.1908

    steps:

    - name: Checking out code
      uses: actions/checkout@v2

    - name: Installing dependencies
      run: |
        yum -y install epel-release rsync unzip mailx bzip2
        yum -y install git make gcc gcc-c++ binutils libX11-devel libXpm-devel libXft-devel libXext-devel
        yum -y install curl less vim wget bc which
        yum -y install libXcomposite libXcursor libXi libXtst libXrandr alsa-lib mesa-libEGL libXdamage mesa-libGL libXScrnSaver
        yum -y install jq

    - name: Installing Anaconda
      run: |
        echo "Install anaconda 2021.11 x86_64"
        wget -q  https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
        echo "fedf9e340039557f7b5e8a8a86affa9d299f5e9820144bd7b92ae9f7ee08ac60  Anaconda3-2021.11-Linux-x86_64.sh" > anaconda_hash_sha256
        sha256sum -c anaconda_hash_sha256
        bash Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/anaconda3
        echo ". /opt/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc
        source ~/.bashrc
        conda update -y -n base -c defaults conda

    - name: Download the Agilepy environment
      run: |
        sttag=`cat sciencetools_version.txt`
        source ~/.bashrc
        conda config --add channels conda-forge
        conda config --add channels plotly
        conda create -y -n agilepydevops -c agilescience agiletools==$sttag agilepy-dataset
        conda activate agilepydevops
        conda env update -f environment.yml

    - name: Running unit tests and code coverage
      run: |
        source ~/.bashrc
        conda activate agilepydevops
        python setup.py develop
        printf "import pkg_resources \npath = pkg_resources.require('agilepy')[0].location \nprint(path+'/agilepy')" > get_agilepy_installation_folder.py
        agilepy_path=$((python get_agilepy_installation_folder.py) 2>&1)
        bash $agilepy_path/scripts/start_coverage.sh

    - name: Uploading coverage report to Codacy
      shell: bash -l {0}
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        CODACY_PROJECT_NAME: ${{ secrets.CODACY_PROJECT_NAME }}
        CODACY_USERNAME: ${{ secrets.CODACY_USERNAME }}
      run: |
        source ~/.bashrc	
        conda activate agilepydevops	
        agilepy_path=$((python get_agilepy_installation_folder.py) 2>&1)
        curl -Ls https://coverage.codacy.com/get.sh -o get.sh
        chmod +x get.sh
        ./get.sh report -r $agilepy_path/testing/unittesting/coverage/cov_xml_report --commit-uuid "$GITHUB_SHA"
    
    - name: Triggering dockerhub for container building
      shell: bash -l {0}
      run: |
        curl -H "Content-Type: application/json" \
        --data '{"source_type": "Branch", "source_name": "develop"}' \
        -X POST "https://hub.docker.com/api/build/v1/source/2e3f2827-4912-486e-9353-43f2e540c25b/trigger/6b916551-0929-46b7-bc2b-74115a63017b/call/"
