name: CI/CD

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-18.04

    container: centos:7.7.1908

    steps:

    - name: Checking out code
      uses: actions/checkout@v2

    - name: Installing dependencies
      run: |
        yum -y install epel-release rsync unzip mailx bzip2 jq
        yum -y install git make gcc gcc-c++ binutils libX11-devel libXpm-devel libXft-devel libXext-devel
        yum -y install curl less vim wget bc which
        yum -y install libXcomposite libXcursor libXi libXtst libXrandr alsa-lib mesa-libEGL libXdamage mesa-libGL libXScrnSaver

    - name: Installing Anaconda
      run: |
        echo "Install anaconda 5.3.0 x86_64"
        wget -q https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh
        echo "cfbf5fe70dd1b797ec677e63c61f8efc92dad930fd1c94d60390bb07fdc09959  Anaconda3-5.3.0-Linux-x86_64.sh" > anaconda_hash_sha256
        sha256sum -c anaconda_hash_sha256
        bash Anaconda3-5.3.0-Linux-x86_64.sh -b -p /opt/anaconda3
        echo ". /opt/anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc
        source ~/.bashrc

    - name: Anaconda info
      run: |
        source ~/.bashrc
        which python
        conda --version

    - name: Download the Agilepy environment
      run: |
        source ~/.bashrc
        conda config --add channels conda-forge
        conda create -n agilepydevops -c agilescience agilepy

    - name: Running unit tests
      run: |
        source ~/.bashrc
        conda activate agilepydevops
        bash start_agilepy_tests.sh

